-- Grüne Gurke · Startinhalte
-- Erzeugt von scripts/generate-seed.mjs – nicht von Hand ändern.
-- Einmalig nach 0001_init.sql ausführen. Ein zweiter Lauf ersetzt die Inhalte
-- und verwirft damit alle Änderungen aus dem Verwaltungsbereich.

begin;

truncate table
  public.menu_item_variants,
  public.menu_items,
  public.menu_categories,
  public.allergens,
  public.menu_notes,
  public.gallery_images,
  public.job_postings,
  public.job_benefits,
  public.opening_seasons,
  public.site_settings
  restart identity cascade;


-- Öffnungszeiten
insert into public.opening_seasons (slug, label, period, start_month, end_month, restaurant_opens, restaurant_closes, takeaway_opens, takeaway_closes, kitchen_until, sort_order) values ('sommer', 'Sommer', '1. Mai – 31. Oktober', 5, 10, '11:00', '22:00', '11:00', '22:00', '21:30', 0);
insert into public.opening_seasons (slug, label, period, start_month, end_month, restaurant_opens, restaurant_closes, takeaway_opens, takeaway_closes, kitchen_until, sort_order) values ('winter', 'Winter', '1. November – 30. April', 11, 4, '11:00', '22:00', '11:00', '21:30', '21:00', 1);

-- Speisekarte
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('suppen', 'Suppen & Appetitmacher', null, null, 0);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Ukrainische Soljanka', 'mit Toast', 560, 'A.G.J.I.1.2.3.4.8', '{}', null, null, 0 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Harzer Schiebensuppe', 'Zwiebelsuppe mit reichlich Fleischklößchen und Graubrot', 560, 'A.C.G.J', '{}', null, null, 1 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Deftige Brühe', 'mit einer Einlage aus Eierstich, edlem Gemüse und Fleischklößchen', 560, 'A.C.J.I', '{}', null, null, 2 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Tomatencremesuppe', 'mit Sahnehäubchen', 590, 'A.G.J', array['veg'], null, null, 3 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Vorsuppe als Sattmacher', 'Jede Vorsuppe auch in großer Portion', 890, null, '{}', null, null, 4 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hausgemachter Erbseneintopf', 'mit Bockwurst', 990, 'A.C.G.F.I.J.L.5', '{}', null, null, 5 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Deftige Nudelsuppe', 'mit Geflügelfleisch, Gemüse und Fleischklößchen', 990, 'A.C.J.I', '{}', null, null, 6 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Überbackenes Würzfleisch', 'mit Sauce Hollandaise überbacken, dazu Toast und Zitrone', 680, 'A.C.G.I.J.D', '{}', null, null, 7 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Karlsbader Schnitte', '2 Toast mit Schinken und Käse überbacken, Semmelbrösel und Garnitur', 880, 'A.C.G.2.3.4', '{}', null, null, 8 from public.menu_categories where slug = 'suppen';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gebackener Camembert', 'mit Preiselbeeren, Toast und Garnitur', 890, 'A.D.G', '{}', null, null, 9 from public.menu_categories where slug = 'suppen';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'als kleines Hauptgericht', 890, 0 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'suppen' and i.name = 'Gebackener Camembert';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'als Vorspeise', 680, 1 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'suppen' and i.name = 'Gebackener Camembert';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('snacks', 'Snacks, Kaltes & belegte Brote', null, null, 1);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Belegtes Brot', 'lecker garniert, wahlweise mit Salami, gekochtem Schinken oder kaltem Braten', 790, 'A.G.1.2.3.4.I.J', '{}', null, null, 0 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Chicke Platte', 'bunt arrangiert – lauter Leckereien mit Butter und Brot', 1450, 'G.A.C.I.J.1.2.3.4', '{}', null, null, 1 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Strammer Max', 'mit Schinkenspeck, Spiegeleiern und Garnitur', 940, 'C.A.G.1', '{}', null, null, 2 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Salamibrot mit Spiegeleiern', 'mit Ketchup und Garnitur', 940, 'G.C.A.J.1.3', '{}', null, null, 3 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Zigeunerbrot', 'mit Garnitur', 1090, 'G.A.C.I.J', '{}', null, null, 4 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schlemmer Toast', 'kleines Steak mit Cremechampignons und Sauce Hollandaise', 1090, 'A.C.G.F.J', '{}', null, null, 5 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Marinierter Hering', 'nach Hausfrauenart mit Salzkartoffeln und Garnitur', 1490, 'A.G.I.J', array['fish'], null, null, 6 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geräucherte Forellenfilets', 'mit Sahnemeerrettich, Butter, Toast und Garnitur', 1290, 'A.G', array['fish'], null, null, 7 from public.menu_categories where slug = 'snacks';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hausgemachte Sülze', 'mit Remouladensoße, Bratkartoffeln und Rohkostsalat', 1550, 'A.C.D.G.J.I.1.2.3.11', '{}', null, null, 8 from public.menu_categories where slug = 'snacks';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('eier', 'Eiergerichte', null, 'Zu den Rühr- und Spiegeleiern gibt es Garnitur und wahlweise Butterbrot, Bratkartoffeln oder Kartoffelsalat.', 2);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Drei Rühreier mit knusprigem Speck', null, 999, 'A.C.2.4', '{}', null, null, 0 from public.menu_categories where slug = 'eier';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Drei Rühreier mit Forellenfilet', 'mit geräuchertem Forellenfilet und Sahnemeerrettich', 1590, 'A.C.G', array['fish'], null, null, 1 from public.menu_categories where slug = 'eier';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Drei Rühreier mit Tomaten', 'mit Tomaten und reichlich Schnittlauch', 1150, 'A.C', array['veg'], null, null, 2 from public.menu_categories where slug = 'eier';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Drei Spiegeleier mit knusprigem Speck', null, 1050, 'A.C.2.4', '{}', null, null, 3 from public.menu_categories where slug = 'eier';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Bauernfrühstück', 'mit Gürkchen und marinierten Salaten', 1450, 'A.C', '{}', null, null, 4 from public.menu_categories where slug = 'eier';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gekochte halbe Eier', 'auf Remouladensoße mit Kochschinkenstreifen, Bratkartoffeln und gemischtem Salat', 1450, 'A.J.G.I.C.2.3.4.11', '{}', null, null, 5 from public.menu_categories where slug = 'eier';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('nudeln', 'Nudeln', null, null, 3);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hausmacher Nudeln', 'mit Rindergulasch und gemischtem Salatteller', 1890, 'A.G.C.I.J.F.11', '{}', null, null, 0 from public.menu_categories where slug = 'nudeln';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spaghetti mit Schinkenwürfeln', 'mit Tomatensoße und gemischtem Salatteller', 1550, 'A.G.C.J.11', '{}', null, null, 1 from public.menu_categories where slug = 'nudeln';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spaghetti Bolognese', 'mit würziger Fleischsoße, Parmesan und gemischtem Salatteller', 1550, 'A.G.C.11', '{}', null, null, 2 from public.menu_categories where slug = 'nudeln';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spaghetti Carbonara', 'mit Sahnesoße, Ei, Schinken und gemischtem Salatteller', 1550, 'A.G.C.2.3.4.11', '{}', null, null, 3 from public.menu_categories where slug = 'nudeln';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spaghetti „à la Genovese“', 'in Basilikumsoße geschwenkt, dazu Putenbruststeaks, Soße „Café de Paris“ und gemischter Salatteller', 1890, 'A.G.C.H.F.11', '{}', null, null, 4 from public.menu_categories where slug = 'nudeln';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spaghetti with Meatballs', 'mit Hackfleischbällchen in Tomatensoße und gemischtem Salatteller', 1550, 'A.G.C.I.F.11', '{}', null, null, 5 from public.menu_categories where slug = 'nudeln';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('salate', 'Salate', '…da ham wir den Salat!', 'Wählen Sie Ihr Dressing selbst: Essig-Öl-Kräuter, Joghurt, Sauerrahm, French, Balsamico oder Cocktail.', 4);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Kleiner Salat', null, 570, 'C.G.11', array['veg'], null, null, 0 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gurkensalat', null, 570, null, array['veg'], null, null, 1 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Unser Spezialsalat', 'verschiedene Blatt- und Gemüsesalate der Saison mit Soße Ihrer Wahl, Butter und Toast', 1199, 'A.C.G', array['veg'], null, null, 2 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spezialsalat mit Schinken & Käse', 'mit gekochtem Schinken, Käse und Joghurtdressing', 1490, 'A.C.G.2.3.4', '{}', null, null, 3 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Spezialsalat mit Schinken & Ei', 'mit gekochtem Schinken, grob gehackten Eiern und Joghurtdressing', 1490, 'A.C.G.2.3.4', '{}', null, null, 4 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Bunter Salat „Virginia Chicken“', 'Spezialsalatmischung mit gegrillter Hähnchenbrust, gerösteten Pistazien und Cocktailsoße', 1590, 'A.H.G.C.J.I', '{}', null, null, 5 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Thunfischsalat „Nizza“', 'Spezialsalatmischung mit Thunfisch, gehackten Eiern, Zwiebelringen und Oliven', 1590, 'C.D', array['fish'], null, null, 6 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Thunfischsalat „Hawaii“', 'mit Thunfisch, Emmentaler, Ananas und Schinkenstreifen', 1590, 'C.G.D.2.3.4', array['fish'], null, null, 7 from public.menu_categories where slug = 'salate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gemüseplatte', 'marinierte und angemachte Salate mit 3 Spiegeleiern auf Bratkartoffeln und Joghurtdressing', 1490, 'C.G.2.3', array['veg'], null, null, 8 from public.menu_categories where slug = 'salate';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('spezialsalate', 'Spezial-Salatkarte', null, 'Wählen Sie Ihr Dressing selbst: Essig-Öl-Kräuter, Joghurt, Sauerrahm, French, Balsamico oder Cocktail.', 5);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Provenzalischer Bauernsalat', 'mit Käse nach Balkanart, Oliven, Peperoni, roten Bohnen und Zwiebeln, dazu Butter und Toast', 1590, 'A.C.G.L', array['veg'], null, null, 0 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Bodetaler Salat', 'mit geräuchertem Forellenfilet und marinierten Pilzen, dazu Butter und Toast – wir empfehlen Joghurtdressing', 1590, 'A.G.J.3', array['fish'], null, null, 1 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Bunter Salat „Louisiana“', 'mit gegrillten Putenmedaillons, Mandarinen, Weintrauben und knusprigen Croutons – wir empfehlen pikante Cocktailsoße', 1590, 'A.G.J', '{}', null, null, 2 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Salat „Mister Roquefort“', 'mit Edelschimmelkäse, Weintrauben und knusprigen Croutons – wir empfehlen Sauerrahmdressing', 1590, 'A.G.J', array['veg'], null, null, 3 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, '„Grüne Gurke“ Chefsalat', 'mit gekochten Eiern, Käse, Schinken, Peperoni, Cocktailtomaten, marinierten Pilzen und knusprigen Croutons', 1590, 'A.C.G.J.2.3.4.11', array['chef'], null, null, 4 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Bunter Salat „Cross Chicken“', 'mit Hähnchenbrust im Knuspermantel, Weintrauben, gerösteten Pistazien und pikanter Cocktailsoße', 1590, 'A.C.H.11', '{}', null, null, 5 from public.menu_categories where slug = 'spezialsalate';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('gefluegel', 'Geflügel', null, null, 6);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Panierte Hähnchenbrust', 'mit Kräuterbutter, jungen Erbsen und Pommes frites', 1990, 'A.C.G', '{}', null, null, 0 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, '2 Hähnchenschenkel', 'knusprig gebraten auf feurig scharfer Soße mit Pommes frites und gemischtem Salatteller', 1790, 'A.C.F.G.J.11', '{}', null, null, 1 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Putenbruststeak „Café de Paris“', 'mit Soße „Café de Paris“, jungen Erbsen und Kartoffelkroketten', 1990, 'A.G.F', '{}', null, null, 2 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Putenbruststeak mit Cremechampignons', 'mit Kartoffelkroketten und gemischtem Salatteller', 1990, 'A.G.F', '{}', null, null, 3 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geflügelbruststreifen in Pfifferlingrahm', 'in Rahmsoße mit Pfifferlingen, Speck, Zwiebelwürfeln und frischen Kräutern, dazu Butterreis und gemischter Salatteller', 1990, 'A.G.2.3', '{}', null, null, 4 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hühnerfrikassee nach Berliner Art', 'mit Spargel, Fleischklößchen, Butterreis und gemischtem Salatteller', 1790, 'A.G.I.F', '{}', null, null, 5 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Chicken Wings', 'gegrillte Hähnchenflügel mit Barbecue-Soße, Limettenspalten, Pommes frites und gemischtem Salatteller', 1790, 'A.G.J.11', '{}', null, null, 6 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gegrillte Hähnchenbruststeaks in Curryrahm', 'in Curryrahmsoße mit leckeren Früchten, Kartoffelkroketten und gemischtem Salatteller', 1990, 'A.C.J.G.I.4.7', '{}', null, null, 7 from public.menu_categories where slug = 'gefluegel';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('fleisch', 'Fleischgerichte', null, null, 7);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gefüllte Rinderroulade', 'mit Apfelrotkohl und Salzkartoffeln', 2190, 'A.I.J.F', '{}', null, null, 0 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Wildragout', 'mit Waldpilzen, Apfelrotkohl und Kartoffelklößen', 2190, 'L.I.A.G', '{}', null, null, 1 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geschmorte Schweinshaxe', 'in deftiger Soße mit Sauerkraut und Salzkartoffeln', 2090, 'A.J.F.I.1', '{}', null, null, 2 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gefüllte Kohlroulade', 'mit Salzkartoffeln und gemischtem Salatteller', 1790, 'C.A.F.J', '{}', null, null, 3 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Rindergulasch', 'mit Apfelrotkohl und Kartoffelklößen', 1990, 'A.J.F.I', '{}', null, null, 4 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Rahmgeschnetzeltes vom Schwein', 'mit Champignons, Butterreis und jungen Erbsen', 1790, 'A.G', '{}', null, null, 5 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gekochtes Eisbein', 'mit Sauerkraut und Erbsenpüree', 1890, 'A.J.L', '{}', 'auf Wunsch mit Sahnemeerrettich', 170, 6 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geschmorte Rippchen', 'mit Sauerkraut und Salzkartoffeln', 1990, 'A.I.F.J', '{}', null, null, 7 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Feuerfleisch', 'mit Bratkartoffeln und gemischtem Salatteller', 1690, 'C.A.F.2.3', '{}', null, null, 8 from public.menu_categories where slug = 'fleisch';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geschmorter Schweinebraten', 'mit Mischgemüse und Salzkartoffeln', 1690, 'C.A.J.G.I', '{}', null, null, 9 from public.menu_categories where slug = 'fleisch';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('hausmannskost', '…und immer noch kein Ende', null, null, 8);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gebratene Leber nach Berliner Art', 'mit gebräunten Zwiebeln und Apfelringen, dazu Erbsenpüree und Weißkrautsalat', 1790, 'A.I.J.F.L', '{}', null, null, 0 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gebratene Leber mit Zwiebeln', 'mit Bratkartoffeln und gemischtem Salatteller', 1690, 'A.2.3', '{}', null, null, 1 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gebratene Leber auf klassische Art', 'mit Kartoffelpüree, Zwiebelsoße und gemischtem Salatteller', 1690, 'A.I.G.C.J.F', '{}', null, null, 2 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Pfannengyros', 'mit Tzatziki, Krautsalat und Pommes frites', 1890, 'A.G.I.J.F', '{}', null, null, 3 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gegrillte Schweinerippchen', 'nach Art des Hauses mariniert und gegrillt, dazu Zigeunersoße, Pommes frites und gemischter Salatteller', 2090, 'A.G.J.F', '{}', null, null, 4 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Paniertes Fischfilet', 'mit Kräuterbutter, Zitronenspalten und gemischtem Salatteller – wahlweise Pommes frites, Bratkartoffeln oder Kartoffelsalat', 1690, 'A.D.G', array['fish'], null, null, 5 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Paniertes Schollenfilet', 'mit Remouladensoße, Zitronenspalten und gemischtem Salatteller – wahlweise Pommes frites, Bratkartoffeln oder Kartoffelsalat', 1790, 'A.D.C.J.G.I.2.11', array['fish'], null, null, 6 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Riesenhacksteak', 'mit Bratkartoffeln, Soße und gemischtem Salatteller', 1690, 'A.C.F.J', '{}', null, null, 7 from public.menu_categories where slug = 'hausmannskost';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'klassisch', 1690, 0 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'hausmannskost' and i.name = 'Riesenhacksteak';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'mit Cremechampignons, Letscho, Pfefferrahmsoße, Spiegeleiern, Zwiebelsoße, Kräuterbutter oder Zigeunersoße', 1890, 1 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'hausmannskost' and i.name = 'Riesenhacksteak';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('pfanne', 'Aus der Pfanne', null, null, 9);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinesteak mit Kräuterbutter', 'mit Pommes frites und jungen Erbsen', 1890, 'A.G', '{}', null, null, 0 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinesteak mit Letscho', 'mit Bratkartoffeln und Gurkensalat', 1890, 'A.2.3', '{}', null, null, 1 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinesteak nach Feinschmeckerart', 'mit Pommes frites und jungen Erbsen', 1999, 'G.I.J.D.A.C', '{}', null, null, 2 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinesteak mit Cremechampignons', 'mit Pommes frites und gemischtem Salatteller', 1890, 'G.F.A', '{}', null, null, 3 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinesteak nach Prager Art', 'mit Schinkenrührei, Bratkartoffeln und jungen Erbsen', 1990, 'A.G.C.2.4', '{}', null, null, 4 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Rostbrätl', 'mit Bratkartoffeln und gemischtem Salatteller', 1890, 'A.F.J.G', '{}', null, null, 5 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Kasseler Steak mit Letscho', 'mit Pommes frites und Gurkensalat', 1890, 'A.1', '{}', null, null, 6 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Kasseler Steak mit 2 Setzeiern', 'mit Bratkartoffeln und gemischtem Salatteller', 1890, 'A.C.1.2.3', '{}', null, null, 7 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Leckere Schaschlyks', 'vom Schwein mit Leber, Gurken, Speck und Zwiebeln, dazu Zigeunersoße, Pommes frites und gemischter Salatteller', 1990, 'A.J.G.2.4', '{}', null, null, 8 from public.menu_categories where slug = 'pfanne';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Großer „Grüne Gurke“ Grillteller', 'gegrillte Leber, kleine Steaks vom Schwein, Kasseler, Hähnchenbrust, kleine Bitoks, knuspriger Speck und Grillwürstchen – dazu 2 verschiedene Soßen, Butterkreation, Kroketten und junge Erbsen', 2290, 'A.I.J.G.F.1.2.3.4.8', array['chef'], null, null, 9 from public.menu_categories where slug = 'pfanne';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('schnitzelparadies', 'Unser Schnitzelparadies', null, null, 10);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gefülltes Schnitzel „Classic“ (Cordon Bleu)', 'mit Käse und Schinken gefüllt, dazu Buttererbsen und Kartoffelkroketten', 2090, 'A.C.G.2.3.4', '{}', null, null, 0 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gefülltes Schnitzel „Athena“', 'mit Käse nach Balkanart und Bauernschinken gefüllt, dazu Buttererbsen und Bratkartoffeln', 2090, 'A.C.G.1', '{}', null, null, 1 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gefülltes Wernigeröder Herrenschnitzel', 'deftig mit Zwiebelmett und Kräutersenf gefüllt, dazu Pfefferrahmsoße, Zwiebelringe, Buttererbsen und Kartoffelkroketten', 2090, 'A.C.G.J.1.3', array['chef'], null, null, 2 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Überbackenes Schweineschnitzel „Feinschmecker Art“', 'mit Würzfleisch, Spargelstücken und Sauce Hollandaise überbacken, dazu Buttererbsen und Kartoffelkroketten', 2250, 'G.I.J.D.A.C', '{}', null, null, 3 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hausspezial „Grüne Gurke Schnitzel – Pikant“', 'mit Schinken und Ananas belegt, mit Käse überbacken, dazu Curryrahmsoße, Pommes frites und gemischter Salatteller', 2199, 'A.C.G.J.I.2.3.4.7', array['chef'], null, null, 4 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hausspezial „Grüne Gurke Schnitzel – Herzhaft“', 'mit Schinken und Tomate belegt, mit Käse überbacken, dazu Pfefferrahmsoße, Pommes frites und gemischter Salatteller', 2199, 'A.C.G.2.3.4', array['chef'], null, null, 5 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Mega Schnitzelteller „Gourmet“', '3 kleine Schnitzel mit Letscho, Cremechampignons und Kräuterbutter, dazu Mischgemüse und Kartoffelkroketten', 2190, 'A.C.G.F', '{}', null, null, 6 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Mailänder Schnitzel', 'mit Tomatensoße, Parmesan, Spaghetti und gemischtem Salatteller', 1990, 'A.C.G.J', '{}', null, null, 7 from public.menu_categories where slug = 'schnitzelparadies';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('schnitzeleien', '…weitere Schnitzeleien', null, 'Unsere Schnitzel wiegen unpaniert 250 Gramm.', 11);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Paniertes Schweineschnitzel', 'in Butter gebraten, mit Pommes frites, Soße und gemischtem Salatteller', 1790, 'A.C.G.J.I', '{}', null, null, 0 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Jägerschnitzel', 'wie oben, mit Cremechampignons', 1990, 'A.C.G.F', '{}', null, null, 1 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Pustaschnitzel', 'wie oben, mit Letschogemüse', 1990, 'A.C.G', '{}', null, null, 2 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Zigeunerschnitzel', 'wie oben, mit Zigeunersoße', 1990, 'A.C.G.J', '{}', null, null, 3 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Zwiebelschnitzel', 'wie oben, mit Zwiebelsoße', 1990, 'A.C.G.J.I.F', '{}', null, null, 4 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hamburger Schnitzel', 'wie oben, mit 2 Setzeiern und Soße', 1990, 'A.C.G.J.I', '{}', null, null, 5 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schnitzel „Pfeffermühle“', 'wie oben, mit Pfefferrahmsoße', 1990, 'A.C.G.3', '{}', null, null, 6 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schnitzel mit Kräuterbutter', 'wie oben, mit Soße', 1990, 'A.C.G.J.I', '{}', null, null, 7 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schnitzel „nach Wiener Art“', 'wie oben, mit Zitronenspalten und Soße', 1990, 'A.C.G.J.I', '{}', null, null, 8 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Nostalgie: Panierte Jagdwurstscheiben', 'in Butter gebraten mit Bratkartoffeln, Soße und gemischtem Salatteller', 1690, 'J.G.C.A.I.1.2.3.8', '{}', null, null, 9 from public.menu_categories where slug = 'schnitzeleien';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'klassisch', 1690, 0 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'schnitzeleien' and i.name = 'Nostalgie: Panierte Jagdwurstscheiben';
insert into public.menu_item_variants (item_id, label, price_cents, sort_order) select i.id, 'mit Cremechampignons, Zigeunersoße, Spiegeleiern, Zwiebelsoße, Kräuterbutter, Pfeffersoße oder Letschogemüse', 1890, 1 from public.menu_items i join public.menu_categories c on c.id = i.category_id where c.slug = 'schnitzeleien' and i.name = 'Nostalgie: Panierte Jagdwurstscheiben';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('kinder', 'Put-Put – die Karte für Kids', '…nichts für Große. Die Karte für Kids, die wissen, was sie wollen!', 'Wählt eure Beilagen selbst aus: Reis, Pommes frites, Kartoffelbrei, Gemüse oder Salat. Spiele, Puzzle, Memory, Malkiste, Bilderbuch … fragt danach!', 12);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Für den Suppenkasper', '1 Teller Tomatensuppe mit Knuspercroutons oder heiße Brühe mit Einlage', 390, 'A.G.J.C.I', '{}', null, null, 0 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Quasselstrippen zum Runterschlürfen', 'Spaghetti mit Tomatensoße, Bolognesesoße oder Käsesahnesoße', 690, 'A.G.C.J', '{}', null, null, 1 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Hühnchen Put-Put', 'panierte Hähnchenbrust, Chicken Wings (5 Stück) oder Frikassee vom Huhn', 750, 'A.G.C.I.F.11', '{}', null, null, 2 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schweinchen Dick – der Rundumsattmachteller', 'kleines Schweineschnitzel mit Soße oder Ketchup, oder kleines Schweinesteak mit Kräuselwurst und Monsterketchup', 750, 'A.J.G.I.C', '{}', null, null, 3 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Obelix’ Original Hinkelstein', 'gebratener Fleischklops', 699, 'A.F.I.C', '{}', null, null, 4 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Räubergulasch', 'mit Gemüse und Kartoffeln', 699, 'G', '{}', null, null, 5 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Unsere Turbo-Schnecke „Mimi Nörgel“', 'Grillwurstschnecke mit Soße oder Ketchup', 699, 'A.J.G.I.C', '{}', null, null, 6 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Fisherman’s Friends', 'knusprige Fischstäbchen mit Ketchup', 499, 'A.D', array['fish'], null, null, 7 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Mount Everest', 'ein Berg Kartoffelbrei mit Kräuselwurst und Ketchup', 699, 'A.G.I.C.J', '{}', null, null, 8 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Smarties-Teller', 'Milchreis mit Zucker, Zimt und vielen, vielen bunten Smarties', 550, 'G.A.7', array['veg'], null, null, 9 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Troll’s Goldtaler', 'Kartoffelpuffer mit Zucker und Apfelmus', 599, 'A.C.F.G.H.3', array['veg'], null, null, 10 from public.menu_categories where slug = 'kinder';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Mega Crossis', 'Portion extra krosse Pommes frites mit Mayo oder Ketchup', 390, 'A.J.C.11', array['veg'], null, null, 11 from public.menu_categories where slug = 'kinder';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('desserts', 'Für danach … & kleine Eiszeit', null, null, 13);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Rote Grütze mit Vanillesoße', null, 580, 'G', array['veg'], null, null, 0 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Erdbeerkompott mit Schlagsahne', null, 499, 'G.3', array['veg'], null, null, 1 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Apfelkompott mit Vanillesoße', null, 499, 'G.3', array['veg'], null, null, 2 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Geschichtetes Schoko-Vanille-Dessert', 'mit Roter Grütze und Sahnetupfer', 580, 'G.D', array['veg'], null, null, 3 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Eis je Kugel', 'Vanille, Schokolade oder Erdbeere', 210, 'G.A.C.E.F.H', array['veg'], null, null, 4 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Schlagsahne', null, 180, 'G', array['veg'], null, null, 5 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Vanilleeis an Roter Grütze', 'mit Sahnetupfer garniert', 680, 'G.A.C.E.F.H', array['veg'], null, null, 6 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Pfirsichbecher', 'mit 3 Kugeln Eis und Sahne', 899, 'G.A.C.E.F.H', array['veg'], null, null, 7 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Erdbeerbecher', '3 Kugeln Eis mit Erdbeerkompott und Sahne', 899, 'G.A.C.E.F.H', array['veg'], null, null, 8 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Mandarinenbecher', 'mit 3 Kugeln Eis und Sahne', 899, 'G.A.C.E.F.H', array['veg'], null, null, 9 from public.menu_categories where slug = 'desserts';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Ananasbecher', 'mit 3 Kugeln Eis und Sahne', 899, 'G.A.C.E.F.H', array['veg'], null, null, 10 from public.menu_categories where slug = 'desserts';
insert into public.menu_categories (slug, title, intro, note, sort_order) values ('knabberzeug', 'Knabberzeug', null, 'Damit der Rahmen dieser Karte nicht gesprengt wird, erfragen Sie bitte andere Mixturen beim Personal.', 14);
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Chipsletten', '1 Packung', 390, null, array['veg'], null, null, 0 from public.menu_categories where slug = 'knabberzeug';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Gesalzene Erdnüsse', '1 Schälchen', 290, 'E', array['veg'], null, null, 1 from public.menu_categories where slug = 'knabberzeug';
insert into public.menu_items (category_id, name, description, price_cents, allergens, tags, extra_label, extra_price_cents, sort_order) select id, 'Salzstangen', '1 Packung', 250, 'A', array['veg'], null, null, 2 from public.menu_categories where slug = 'knabberzeug';

-- Zusatzstoffe und Allergene
insert into public.allergens (code, label, sort_order) values ('A', 'Weizen (glutenhaltig)', 0);
insert into public.allergens (code, label, sort_order) values ('a', 'Gerste (glutenhaltig)', 1);
insert into public.allergens (code, label, sort_order) values ('B', 'Krebstiere', 2);
insert into public.allergens (code, label, sort_order) values ('C', 'Eier', 3);
insert into public.allergens (code, label, sort_order) values ('D', 'Fisch', 4);
insert into public.allergens (code, label, sort_order) values ('E', 'Erdnüsse', 5);
insert into public.allergens (code, label, sort_order) values ('F', 'Soja', 6);
insert into public.allergens (code, label, sort_order) values ('G', 'Milch / Laktose', 7);
insert into public.allergens (code, label, sort_order) values ('H', 'Schalenfrüchte', 8);
insert into public.allergens (code, label, sort_order) values ('I', 'Sellerie', 9);
insert into public.allergens (code, label, sort_order) values ('J', 'Senf', 10);
insert into public.allergens (code, label, sort_order) values ('K', 'Sesam', 11);
insert into public.allergens (code, label, sort_order) values ('L', 'Schwefeldioxid, Sulfite', 12);
insert into public.allergens (code, label, sort_order) values ('M', 'Lupinen', 13);
insert into public.allergens (code, label, sort_order) values ('N', 'Weichtiere', 14);
insert into public.allergens (code, label, sort_order) values ('1', 'Konservierungsstoff Natriumnitrit', 15);
insert into public.allergens (code, label, sort_order) values ('2', 'Konservierungsstoff', 16);
insert into public.allergens (code, label, sort_order) values ('3', 'Antioxidationsmittel', 17);
insert into public.allergens (code, label, sort_order) values ('4', 'Geschmacksverstärker', 18);
insert into public.allergens (code, label, sort_order) values ('5', 'geschwefelt', 19);
insert into public.allergens (code, label, sort_order) values ('6', 'chininhaltig', 20);
insert into public.allergens (code, label, sort_order) values ('7', 'Farbstoff', 21);
insert into public.allergens (code, label, sort_order) values ('8', 'Phosphat', 22);
insert into public.allergens (code, label, sort_order) values ('9', 'enthält eine Phenylalaninquelle', 23);
insert into public.allergens (code, label, sort_order) values ('10', 'coffeinhaltig', 24);
insert into public.allergens (code, label, sort_order) values ('11', 'Süßungsmittel', 25);

-- Hinweise unter der Karte
insert into public.menu_notes (text, sort_order) values ('Alle Gerichte gibt es auch zum Mitnehmen.', 0);
insert into public.menu_notes (text, sort_order) values ('Beilagenwechsel oder Extrawünsche kosten extra.', 1);
insert into public.menu_notes (text, sort_order) values ('Die meisten Gerichte gibt es auch als Seniorenteller. Etwas kleinere Portionen, 1,90 € Preisnachlass.', 2);
insert into public.menu_notes (text, sort_order) values ('Alle Preise verstehen sich incl. 19 % Mehrwertsteuer.', 3);
insert into public.menu_notes (text, sort_order) values ('Wir haben täglich ab 11.00 Uhr geöffnet, mit Ausnahme von Heiligabend. Am 1. und 2. Weihnachtsfeiertag nur bis 15:00 Uhr.', 4);

-- Galerie
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/terrace.jpg', 'Sonnige Sommerterrasse mit Sonnenschirmen und grünen Stühlen', 'restaurant', 1200, 900, 0);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-25.jpg', 'Terrasse mit Blumenkübeln und Sonnenschirmen', 'restaurant', 1200, 698, 1);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/exterior.jpg', 'Eingang der Gaststätte Grüne Gurke mit grünen Fensterläden', 'restaurant', 600, 360, 2);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-2.jpg', 'Holzvertäfelte Gaststube mit festlich eingedeckten Tischen', 'restaurant', 1200, 900, 3);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-42.jpg', 'Gastraum mit Laternen, Vitrinenschrank und weißen Tischdecken', 'restaurant', 1200, 900, 4);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-16.jpg', 'Eingedeckte Tische mit orangefarbenen Servietten', 'restaurant', 1200, 900, 5);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-36.jpg', 'Lange Festtafel mit Rosen und gefalteten Servietten', 'restaurant', 1200, 900, 6);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-31.jpg', 'Festtafel mit grünen Kerzen und roten Stühlen', 'restaurant', 1200, 900, 7);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-13.jpg', 'Festlich gedeckter Tisch mit hellgrünen Servietten am Fenster', 'restaurant', 1200, 900, 8);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/restaurant/room-34.jpg', 'Tisch mit roter Rose und rot-weißen Servietten', 'restaurant', 1200, 900, 9);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-28.jpg', 'Kaltes Buffet mit Platten, Räucherlachs und Käse', 'catering', 1200, 900, 10);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-1.jpg', 'Platte mit Schinkenröllchen, gefüllten Eiern und Kaviar', 'catering', 1200, 900, 11);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-20.jpg', 'Canapés und Spieße auf dem Partybuffet', 'catering', 1200, 900, 12);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-22.jpg', 'Reich dekoriertes Buffet mit Fisch- und Fleischplatten', 'catering', 1200, 900, 13);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-13.jpg', 'Buffet mit Aufschnitt, Salaten und Garnituren', 'catering', 1200, 900, 14);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-17.jpg', 'Dessertgläser mit Götterspeise und Mousse', 'catering', 1200, 900, 15);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-24.jpg', 'Dessertplatte mit Terrinen, Kuchen und Götterspeise', 'catering', 1200, 900, 16);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-25.jpg', 'Buffettisch mit Holzbrettern voller Häppchen', 'catering', 1200, 900, 17);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-12.jpg', 'Festbuffet mit vielen Platten im Saal', 'catering', 1200, 900, 18);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-21.jpg', 'Gemüseplatte mit Spargel, Blumenkohl und Rotkohl', 'catering', 1200, 900, 19);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-32.jpg', 'Erdbeerbowle in der Glasschale', 'catering', 900, 1200, 20);
insert into public.gallery_images (url, alt, category, width, height, sort_order) values ('/images/catering/catering-30.jpg', 'Rinderroulade mit Salzkartoffeln und Apfelrotkohl', 'catering', 1200, 900, 21);

-- Jobs
insert into public.job_postings (title, terms, sort_order) values ('Koch (w/m/d)', 'ab sofort in Vollzeit / Teilzeit / Pauschal', 0);
insert into public.job_postings (title, terms, sort_order) values ('Beikoch (w/m/d)', 'ab sofort in Vollzeit / Teilzeit / Pauschal', 1);
insert into public.job_benefits (label, sort_order) values ('5-Tage-Woche', 0);
insert into public.job_benefits (label, sort_order) values ('Gutes Grundgehalt', 1);
insert into public.job_benefits (label, sort_order) values ('Jahresurlaubsplanung', 2);
insert into public.job_benefits (label, sort_order) values ('Feiertagszuschläge', 3);
insert into public.job_benefits (label, sort_order) values ('Überstundenvergütung', 4);

-- Einstellungen
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('banner_text', 'Bestellungen und Reservierungen unter', 'Hinweisleiste oben', 'Steht ganz oben auf jeder Seite, direkt vor der Telefonnummer.', false, 0);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('hours_note', 'Täglich ab 11 Uhr geöffnet, mit Ausnahme von Heiligabend. Am 1. und 2. Weihnachtsfeiertag nur bis 15:00 Uhr.', 'Hinweis unter den Öffnungszeiten', 'Erscheint unter der Tabelle mit den Öffnungszeiten, zum Beispiel für Feiertage.', true, 1);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('order_note', 'Alle Gerichte und Getränke auch zum Abholen und Mitnehmen! Aufgrund der aktuellen Situation sind ggf. nicht alle Gerichte verfügbar.', 'Hinweis zum Bestellen', 'Steht auf der Startseite und über der Speisekarte im grünen Kasten.', true, 2);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('menu_intro', 'Suppen, Vorspeisen, Eiergerichte, Nudelgerichte, Salate, Geflügelgerichte, Fleischgerichte, Pfannengerichte, Schnitzelparadies, Dessert und Eis, Knabberzeug, Kindergerichte und Spargelgerichte.', 'Einleitung der Speisekarte', 'Die Aufzählung der Kategorien oben auf der Seite „Speisekarte“.', true, 3);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('seasonal_menu_note', '…zur Osterzeit, …zur Spargelzeit, …zur Grünkohlzeit, …zur Weihnachtszeit. Lassen Sie sich überraschen!', 'Saisonkarte', 'Der Kasten „Hier steckt unsere Saisonkarte“ unter der Speisekarte.', true, 4);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('jobs_intro', 'Wir suchen Verstärkung für unser Team!', 'Überschrift auf der Jobseite', 'Die große Zeile auf der Seite „Jobs“ und im Kasten auf der Startseite.', false, 5);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('jobs_application_address', 'GastRoland UG (haftungsbeschränkt)
Friedrich-August-Str. 1, 38889 Blankenburg', 'Anschrift für Bewerbungen', 'Steht auf der Jobseite im Kasten „Bewerbung“.', true, 6);
insert into public.site_settings (key, value, label, hint, multiline, sort_order) values ('events_intro', 'Wir beraten Sie gern und können Ihnen aus einem reichhaltigen Sortiment ein maßgeschneidertes Angebot erstellen. Sie brauchen sich nur zu entscheiden und die Feier kann starten, um den Rest kümmern wir uns!', 'Text zu Feiern & Catering', 'Erscheint auf den Seiten „Feiern & Catering“, „Galerie“ und „Kontakt“.', true, 7);

commit;
